"""DagHooks Protocol."""

from __future__ import annotations

from typing import Protocol

from ghdag.core.models.dag import Task
from ghdag.core.models.metrics import TaskMetrics


class DagHooks(Protocol):
    def on_task_start(self, uuid: str, task: Task) -> None: ...
    def on_task_success(self, uuid: str, task: Task, metrics: TaskMetrics) -> None: ...
    def on_task_failure(self, uuid: str, task: Task, returncode: int, stderr_text: str, metrics: TaskMetrics) -> None: ...
    def on_task_rejected(self, uuid: str, task: Task, retry_depth: int, is_final: bool, metrics: TaskMetrics) -> None: ...
    def on_task_dep_failed(self, uuid: str, task: Task, failed_dep: str) -> None: ...
    def on_task_empty_result(self, uuid: str, task: Task, stderr_text: str, metrics: TaskMetrics) -> None: ...
    def on_shutdown(self, signum: int) -> None: ...
    def check_rejected(self, result_path: str) -> bool: ...
    def check_pipeline_status(self, result_path: str) -> "str | None": ...
    def check_promote_target(self, result_path: str) -> "str | None": ...
